name: Hello

on:
  push:
    branches:
      master

jobs:
  print_hello:
    runs-on: ubuntu-18.04
    steps:
      - name: Print Hello
        run: echo "Hello World!"
      - name: Print Date
        run: date
      - name: Print Directory
        run: ls -l